[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/visit"
  to = "/.netlify/functions/visit"
  status = 200

[[redirects]]
  from = "/api/error-report"
  to = "/.netlify/functions/error-report"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback"
  status = 200

[[redirects]]
  from = "/download/*"
  to = "/.netlify/functions/download"
  status = 200

